import type { Metadata } from "next";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { Inter } from "next/font/google";
import "./globals.css";
import { darkTheme } from "./theme/MainTheme";
import { ThemeProvider } from "@mui/material/styles";
import MaterialNextProvider from "./theme/MaterialNextProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MaterialNextProvider>
          {children}
        </MaterialNextProvider>
      </body>
    </html>
  );
}
