import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MaterialNextProvider from "./theme/MaterialNextProvider";

import AppNavbar from "./components/AppNavbar/AppNavbar";
import BottomNavigationBar from "./components/BottomNavigationBar/BottomNavigationBar";
import Box from "@mui/material/Box"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <MaterialNextProvider>
          <AppNavbar />
          {children}
          <Box height={60}/>
          <BottomNavigationBar />
        </MaterialNextProvider>
      </body>
    </html>
  );
}
